### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by YangXS** [cesc-park/CRCN#10]
Where is the evaluation code to get the results reported in the paper ?

**Comment by cesc-park** [comment]
Sorry,  we did not put our evaluation codes because it included codes to evaluate other baseline models.

**Comment by YangXS** [comment]
Thanks for your reply.

I try to evaluate the results obtained by the generate_output.py using the COCO evaluation metrics:

```python


from coco_evaluation import COCOScorer

count=0
sentences_gts = {}
for i,tests in enumerate(testset):
    for j in range(len(tests[1])):
        #print len(tests[1][j]['sentences'])
        sentences_dicts = []
        for k in range(len(tests[1][j]['sentences'])):
            sentences_dicts.append({'caption':tests[1][j]['sentences'][k]['raw']})
            #print tests[1][j]['sentences'][k]['raw']
        sentences_gts[str(count)] = sentences_dicts
        count += 1

pkl_file = open('output_rcn.p', 'rb')
data1 = pickle.load(pkl_file)
sentences_samples = {}
count = 0
IDs = []
for dataitem in data1:
    for dataitemitem in dataitem:
        sentences_samples[str(count)] = [{'caption': dataitemitem}]
        IDs.append(str(count))
        count += 1

scorer = COCOScorer()
scorer.score(sentences_gts, sentences_samples, IDs)
```

However, the results are really small:

Bleu_1: 0.098
Bleu_2: 0.025
Bleu_3: 0.007
Bleu_4: 0.002

Could you please give me some advises for implementing the correct evaluation ?

**Comment by cesc-park** [comment]
Did you get the results from example data?
The example data is only a part of the data because of the size of the file.

**Comment by YangXS** [comment]
Yes, the evaluated results are obtained from the example dataset.
Would you release the full data used in the paper ?
Thank you.

**Comment by cesc-park** [comment]
There is a problem with the file size and copyright issue of blogs. I will email you a link to download dataset. It should be used for research purposes only and should not be redistributed.

**Comment by cesc-park** [comment]
I will close this issue.
Thanks.
